### PR TITLE
Use URL object in share sheet item

### PR DESCRIPTION
**Pull request by ktprograms**
Allows using URL-specific share sheet actions.

Fix: #325

### CODE REVIEW

**Comment by anohren** [comment]
It might read better to shorten the six lines for `items` into one through nil coalescing

**Comment by ktprograms** [comment]
Diff [e6f0a45...6c30d67](https://github.com/OdyseeTeam/odysee-ios/compare/e6f0a4571fd6f245c29c42bd2467593fba5a5b22..6c30d67282f1103eac7254abef1a6d2a106030ef):
Use nil coalescing for creating share item

**Review by akinwale — APPROVED** [review]
Looks good. Thanks.

**Comment by ktprograms** [comment]
On Fri Jul 8, 2022 at 9:51 AM +08, anohren wrote:
> As long as the type annotation is `[Any]` the types should all be inferred as `Any`. Does that not work?
>
>     let items: [Any] = [ URL(string: url) ?? url ]

Ah, Thanks! Didn't know it worked like that.

**Pull request merged**
