### PR TITLE
Add player rate and jump 10 secs forward/back buttons

### PR DESCRIPTION
**Pull request by ktprograms**
Add control views and subclass AVPlayerViewController to intercept
touches and replicate hiding/showing behaviour of built-in controls.

Use pull-down menu for player rate on >=iOS 14, use picker alert for
older iOS versions.

Fix: #276 (Does not show total change)
Fix: #18 (Maybe use suggested libraries in future?)

### CODE REVIEW

**Comment by ktprograms** [comment]
Just tested, controls are still shown when viewing text content.

Will fix next week.

**Comment by ktprograms** [comment]
Diff [8ccc871...70a576f](https://github.com/OdyseeTeam/odysee-ios/compare/8ccc87186c7439b9993396e86ad4e160c65e953d..70a576ffed6a48dc4398243c5687018100259f7f)
Hide player control views, only unhide when initializing `avpc`

**Comment by ktprograms** [comment]
Diff [70a576f...6b8abd1](https://github.com/OdyseeTeam/odysee-ios/compare/70a576ffed6a48dc4398243c5687018100259f7f..6b8abd169fc0310923c73ae5284c3ec475f39d76)
Move speed button configuration to `viewDidLoad`

**Comment by tzarebczan** [comment]
Keith will take another shot at using another library.

**Comment by ktprograms** [comment]
@tzarebczan I took a look at the libraries suggested in #18, but the first two seem unmaintained, and the third doesn't have any UI controls.

Can you try running this and see if the sync between the custom controls and built in controls seems good enough?

**Comment by tzarebczan** [comment]
@akinwale can you get this merged and into testflight? Probably better than nothing...

**Pull request merged**
