### PR TITLE
iPad support

### PR DESCRIPTION
**Pull request by ktprograms**
Fix: #6

~~Draft: Waiting for discussion and for https://github.com/shogo4405/HaishinKit.swift/issues/997 to be fixed.~~ Not possible, just show warning not to use Multitasking.

### Specify sourceView when creating UIActivityViewController

Fix crash on iPad when tapping share button.

### Increase Media View height on iPads

Save and restore media view height from constraint instead of hardcoding

### CODE REVIEW

**Comment by ktprograms** [comment]
## Commit in latest push
### Fix livestream preview not filling screen, show Multitasking warning
Camera access is not allowed while Multitasking.
https://developer.apple.com/documentation/avkit/accessing_the_camera_while_multitasking

**Comment by ktprograms** [comment]
@akinwale This should be fine to Rebase merge, keeps the commit history clear as there's a few separate changes.

**Comment by akinwale** [comment]
@ktprograms Please fix the merge conflict so that I can create  the test  build.

**Comment by ktprograms** [comment]
@akinwale Done :)

**Pull request merged**
