### PR TITLE
Proper Now Playing and PiP support

### PR DESCRIPTION
**Pull request by ktprograms**
Now Playing and improved player seek code from
https://developer.apple.com/documentation/mediaplayer/becoming_a_now_playable_app/

- Use lazyPlayer for data to put in Now Playing.
- Observe playback rate and playback status and update in Now Playing
  data.
- Add Playback Rate, Skip Backward, Skip Forward and Playback Position
  commands to Now Playing.
- Setup now playing controls when playback starts (instead of when going
  to background).
- Add setting to configure whether playback changes to Audio Only or
  Picture in Picture when app goes to background.
  Note: PiP sometimes doesn't automatically start when backgrounding
  from split view. This seems to be related to the scene width, and it
  also happens with other apps (the Apple Developer app).
- Only disconnect player when scene enters background. This keeps video
  visible while in the app switcher, or changing width in split view.
- Stop Now Playing, External controls and AirPlay when closing mini
  player in-app.

Fix: #226
Fix: #338

### CODE REVIEW

**Comment by ktprograms** [comment]
Diff [7c812ba...aa8b644](https://github.com/OdyseeTeam/odysee-ios/compare/7c812ba89d60ce74f779cb000711072552953375..aa8b644c52be1fd8bbaf4ff4c75864c9c88d79e6):
Fix Lint errors

**Review by akinwale — APPROVED** [review]
Looks good. Thanks.

**Comment by anohren** [comment]
Looking forward to trying this out later!

**Comment by anohren** [comment]
Nice work!

There are still a few quirks on iOS 15.5 but it's possible to watch in PiP now

**Pull request merged**
